#encoding: utf-8
# This file should tain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

tags = Tag.create([{ name:'Noticias' }, { name:'Conciertos' }, { name:'Música' }])
# admin =  Admin.create(email:'info@porinstinto.com', password:'PiManager14')
certs = Concert.create([
              {date: DateTime.new(  2013,4,19  , 22), place:'  Madrid', concert_hall:'  Sala Bar&Co ', tickets:'5€', bands:'   Debruces ', notes:' ', event_link:'  https://www.facebook.com/events/447083582035910/ '},
              {date: DateTime.new(  2013,2,22  , 21), place:'  Vallecas (Madrid) ', concert_hall:'  Sala Hebe ', tickets:'5€', bands:'   Vereda y Ni Media Ni Guarra', notes:' ', event_link:'  https://www.facebook.com/events/444553055617414/444789888927064/?notif_t=plan_mall_activity'}, 
              {date: DateTime.new(  2013,1,11  , 21,30), place:'  Hortaleza (Madrid)', concert_hall:'  Rock Estatal Club ', tickets:'   Entrada gratuita.', bands:'  ', notes:' Acústico, rueda de prensa y escucha del disco ', event_link:'  https://www.facebook.com/events/111211475719703/ '}, 
              {date: DateTime.new(  2012,12,15  , 22), place:'  Madrid', concert_hall:'  Sala Cadillac Solitario ', tickets:'   Entrada gratuita.', bands:'   Producto Bruto ', notes:' ', event_link:'  https://www.facebook.com/events/471298229575287/ '}, 
              {date: DateTime.new(  2012,12,14  , 21), place:'  Vallecas (Madrid) ', concert_hall:'  Sala Hebe ', tickets:'7€', bands:'   Metal Midas y Decoy', notes:' ', event_link:'  https://www.facebook.com/events/121372318023348/?ref=22'}, 
              {date: DateTime.new(  2012,11,24  , 22), place:'  Moratalaz (Madrid)', concert_hall:'  Sala Silikona ', tickets:'5€', bands:'   Fabes con  Almejes ', notes:' ', event_link:'  https://www.facebook.com/events/373319586085475/ '}, 
              {date: DateTime.new(  2012,9,7  ), place:'  Medinilla (Ávila) ', concert_hall:'  Plaza ayuntamiento', tickets:'   Entrada gratuita.', bands:'   Falsa Monea', notes:' ', event_link:' '}, 
              {date: DateTime.new(  2012,6,1  , 22), place:'  Madrid', concert_hall:'  Sala La Siesta', tickets:'5€', bands:'   Vereda ', notes:' ', event_link:'  https://www.facebook.com/events/392983270737658/?ref=22'}, 
              {date: DateTime.new(  2012,5,25  , 20), place:'  Villaviciosa de Odón (Madrid) ', concert_hall:'  Universidad Europea de Madrid ', tickets:'   Entrada gratuita.', bands:'  ', notes:' Festival Sound Spirit ', event_link:' '}, 
              {date: DateTime.new(  2012,5,5  , 20), place:'  Madrid', concert_hall:'  Sala Cabaret', tickets:'5€', bands:'   La Droguería ', notes:' ', event_link:'  https://www.facebook.com/events/312861222117628/ '}, 
              {date: DateTime.new(  2012,3,3  , 23), place:'  Coslada (Madrid)', concert_hall:'  Sensorama Jazz Café ', tickets:'   Entrada gratuita.', bands:'   Eterno Retorno ', notes:' ', event_link:'  https://www.facebook.com/events/282754675128879/ '}, 
              {date: DateTime.new(  2013,9,20  , 21,30), place:'  Madrid', concert_hall:'  Sala Plugged Rockside ', tickets:'   Entrada gratuita.', bands:'   Carta Baladí, Carta Blanca y MalaNoche ', notes:' ', event_link:'  https://www.facebook.com/events/597972446920345/598616543522602/?notif_t=plan_mall_activity'}, 
              {date: DateTime.new(  2013,7,27  , 1), place:'  Barriopedro (Guadalajara) ', concert_hall:'  Plaza del pueblo', tickets:'   Entrada gratuita.', bands:'  ', notes:' Fiestas populares ', event_link:'  https://www.facebook.com/events/684192254930448/ '}, 
              {date: DateTime.new(  2013,6,21  , 21), place:'  Madrid (Vallecas) ', concert_hall:'  Sala Hebe ', tickets:'5€', bands:'    Ni Media Ni Guarra y Kalandrakas', notes:' Fiesta Rockpress', event_link:'  https://www.facebook.com/events/523060271090072/?ref=23'}, 
              {date: DateTime.new(  2013,6,15  , 12), place:'  Madrid (Hortaleza)', concert_hall:'  Breaking Bar', tickets:'   Entrada gratuita.', bands:'  ', notes:' Acústico, XI Aniversario Rock Estatal ', event_link:'  https://www.facebook.com/events/514268831955374/ '}, 
              {date: DateTime.new(  2013,5,25  , 22), place:'  Madrid (Hortaleza)', concert_hall:'  Auditorio Pilar García Peña ', tickets:'   Entrada gratuita.', bands:'  ', notes:' Certamen de bandas Roberto Mira ', event_link:' '}, 
              {date: DateTime.new(  2013,5,18  , 22), place:'  Madrid', concert_hall:'  Plugged Rock Side ', tickets:'   Entrada gratuita.', bands:'   Azote', notes:' ', event_link:'  https://www.facebook.com/events/258789487601141/?ref=23'}, 
              {date: DateTime.new(  2013,5,11  , 20), place:'  Madrid (Vallecas) ', concert_hall:'  Sala Jimmy Jazz ', tickets:'6€', bands:'    Debruces y Xuorum ', notes:' IV Gaser Festival ', event_link:'  https://www.facebook.com/events/368461853264416/ '}, 
              {date: DateTime.new(  2013,10,25  , 22), place:'  Madrid', concert_hall:'  La Leyenda Rock Bar ', tickets:'5€', bands:'   Mala Muñeca', notes:' ', event_link:'  https://www.facebook.com/events/490489387725421'}, 
              {date: DateTime.new(  2013,10,26  , 21,30), place:'  Parla (Madrid)', concert_hall:'  Let\'s Go', tickets:'3€', bands:'   Debruces ', notes:' ', event_link:' '}, 
              {date: DateTime.new(  2013,12,27  , 22), place:'  Madrid', concert_hall:'  La Leyenda Rock Bar ', tickets:'5€', bands:'   Historias Prohibidas ', notes:' ', event_link:'  https://www.facebook.com/events/1433900240154928/'}, 
              {date: DateTime.new(  2013,11,16  , 21,30), place:'  Madrid', concert_hall:'  Sala Cabaret', tickets:'6€', bands:'   Viernes Trozo', notes:'  I Festival Ambulante Rock', event_link:'  https://www.facebook.com/events/169366793263137/ '}, 
              {date: DateTime.new(  2014,1,18  , 22), place:'  Madrid', concert_hall:'  Sala Plugged Rockside ', tickets:'5€', bands:'   A Contraverso y Surko', notes:' ', event_link:'  https://www.facebook.com/events/178840198982578/ '}, 
              {date: DateTime.new(  2013,12,19  , 21,30), place:'  Madrid (Vallecas) ', concert_hall:'  Sala Hebe ', tickets:'   Entrada gratuita.', bands:'   Demente en Blanco', notes:' ', event_link:'  https://www.facebook.com/events/180904762110929/ '}, 
              {date: DateTime.new(  2014,2,15  , 22), place:'  Madrid', concert_hall:'  Sala Plugged Rockside ', tickets:'   Entrada gratuita.', bands:'   Historias Prohibidas y Alfre Camarote ', notes:' ', event_link:'  https://www.facebook.com/events/131770816993651/ '}, 
              {date: DateTime.new(  2014,3,8  , 23), place:'  Torrelaguna ', concert_hall:'  Sala Alchemy', tickets:'   Entrada gratuita.', bands:'   Debruces y monólogo de Juanje Gómez ', notes:' ', event_link:'  https://www.facebook.com/events/451670494967921/ '}, 
              {date: DateTime.new(  2014,4,4  , 20,30), place:'  Madrid', concert_hall:'  Sala Lemon', tickets:'   10€, 8€ anticipada.', bands:'   Gérmenes', notes:' ', event_link:'  https://www.facebook.com/events/222349381294859/222350491294748/ '}, 
              {date: DateTime.new(  2014,3,29  , 20), place:'  Erandio (Bizkaia) ', concert_hall:'  Sala Sentinel ', tickets:'6€', bands:'   Txabolo 13 y Debruces', notes:' ', event_link:' '}, 
              {date: DateTime.new(  2014,6,6  , 20,30), place:'  Aluche, Madrid', concert_hall:'  Auditorio del Parque Alcalde Carlos Arias ', tickets:'   Entrada gratuita.', bands:'  ', notes:' Festival Latina Joven ', event_link:' '}, 
              {date: DateTime.new(  2014,6,7  , 21), place:'  Madrid (Vallecas) ', concert_hall:'  Sala Hebe ', tickets:'5€', bands:'   Kalandrakas, Re,z y 1984', notes:' Presentación del recopilatorio "Latidos de Rocanrol Vol. 3" ', event_link:'  http://ticketandgo.es/eventos/re-z-kalandrakas-por-instinto-1984 '}, 
              {date: DateTime.new(  2014,6,28  , 21), place:'  Madrid (Vallecas) ', concert_hall:'  Sala Hebe ', tickets:'5€', bands:'   Historias Prohibidas y Varo V', notes:' Concierto de despedida de Historias Prohibidas', event_link:'  https://www.facebook.com/events/293928137449847'}, 
              {date: DateTime.new(  2014,8,8  ), place:'  Nogarejas, León ', concert_hall:'  Plaza del pueblo', tickets:'   Entrada gratuita.', bands:'   Dementes y No Konforme ', notes:' ', event_link:' '}

            ])